language: java

script: mvn test

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

after_success:
   - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
